#include<stdio.h>
#include<conio.h>
#include<windows.h>
#include<string.h>
#include<stdlib.h>
/**********
Regn No: 11602432
Sec: K1611 G1
Roll No: 28
Name: Venkata Seshaiah
Lovely Professional University
Mini Project Budget Calculator
**********/
void view_income();
FILE *kp;
void check_fun(){
if(kp==NULL){
	system("cls");
	printf("Problem in Opening Of File");
	exit(0);
}
}
void gotoxy(int x,int y){
	COORD pos = {x,y};
	SetConsoleCursorPosition(GetStdHandle(STD_OUTPUT_HANDLE),pos);
}
struct income{
	float donations,grants,misc;
};
struct expences{
float Account_ing,Bank_Charges,Board_Expense,Conferences,Liability_Insurance,
	Misc,Office_Equipment,Office_Supplies,Payroll_Expenses,Post_Ship,
	Print,Rent,Travel,Utility,Internet;
};
struct expences  dec;
struct income  inc;
int main(){
	int exitopt,income_opt,expenc_opt,view_inc,modify_info;
	char option[1];
	system("cls");
	while(true)
	{
gotoxy(20,6);
printf("Please select one of the option:-");
gotoxy(20,9);
printf("Press[1] for Addition Of Income");
gotoxy(20,11);
printf("Press[2] for Addition Of Expences");
gotoxy(20,13);
printf("Press[3] for Viewing Income");
gotoxy(20,15);
printf("Press[4] for Modifying Income");
gotoxy(20,17);
printf("Press[0] for Exiting the APP");
gotoxy(20,19);
printf("Enter Your Option : ");
scanf("%s",option);
income_opt=strcmp(option,"1");
expenc_opt=strcmp(option,"2");
view_inc=strcmp(option,"3");
modify_info=strcmp(option,"4");
exitopt=strcmp(option,"0");
gotoxy(20,20);
if(exitopt==0){
	system("cls");
	gotoxy(20,10);
	printf("The Application is Going To Exit Press Any Key");
	exit(0);
}
if(income_opt==0){
	system("cls");
	char c[1];
	while(true){
	gotoxy(20,6);
	printf("Add Donations           Press[1]");
	gotoxy(20,8);
	printf("Add Grants              Press[2]");
	gotoxy(20,10);
	printf("Add Miscellaneous       Press[3]");
	gotoxy(20,12);
	printf("Return To Previous Menu Press[0]");
	scanf("%s",c);
	if(strcmp(c,"1")==0)
	{
	    kp=fopen("Calculator.txt","a");
	    check_fun();
		gotoxy(20,14);
		printf("Enter Donations: ");
		scanf("%f",&inc.donations);
		fseek(kp,0,0);
		fprintf(kp,"%f",inc.donations);
		gotoxy(20,16);
		printf("Data Saved Press Enter");
		fclose(kp);
		getch();
	}
	if(strcmp(c,"2")==0)
        {
        kp=fopen("Calculator.txt","a");
        check_fun();
		gotoxy(20,14);
		printf("Enter Grants: ");
		scanf("%f",&inc.grants);
		fseek(kp,18,0);
		fprintf(kp,"%f",inc.grants);
		gotoxy(20,16);
		printf("Data Saved Press Enter");
        fclose(kp);
		getch();
	}
		if(strcmp(c,"3")==0){
        kp=fopen("Calculator.txt","a");
        check_fun();
		gotoxy(20,14);
		printf("Enter Miscellaneous : ");
		scanf("%f",&inc.misc);
		fseek(kp,36,0);
        fprintf(kp,"%f",inc.misc);
		gotoxy(20,16);
		printf("Data Saved Press Enter");
		fclose(kp);
		getch();
	}
		if(strcmp(c,"0")==0){
			system("cls");
			break;
	}
	if(!(strcmp(c,"1")==0 ||strcmp(c,"2") ==0 || strcmp(c,"3")==0 || strcmp(c,"0")==0)){
		gotoxy(16,16);
		printf("Wrong Choice Choose The Right One Please Press Enter To Continue");
		getch();
	}system("cls");
}system("cls");
}
if(expenc_opt==0)
    {
system("cls");
char b[1];
while(true){
	gotoxy(20,7);
	printf("Add Accounting           Press[1]");
	gotoxy(20,8);
	printf("Add Bank Charges         Press[2]");
	gotoxy(20,9);
	printf("Add Board Expence        Press[3]");
	gotoxy(20,10);
	printf("Add Conference           Press[4]");
	gotoxy(20,11);
	printf("Add Liability Insurance  Press[5]");
	gotoxy(20,12);
	printf("Add Miscellaneous        Press[6]");
	gotoxy(20,13);
	printf("Add Office Equipment     Press[7]");
	gotoxy(20,14);
	printf("Add Office Supplies      Press[8]");
	gotoxy(20,15);
	printf("Add Payroll expences     Press[9]");
	gotoxy(20,16);
	printf("Add Postage Shipping     Press[10]");
	gotoxy(20,17);
	printf("Add Printing             Press[11]");
	gotoxy(20,18);
	printf("Add Rent                 Press[12]");
	gotoxy(20,19);
	printf("Add Travel               Press[13]");
	gotoxy(20,20);
	printf("Add Utilities            Press[14]");
	gotoxy(20,21);
	printf("Add Internet             Press[15]");
	gotoxy(20,22);
	printf("Return To Previous Menu  Press[0]");
	gotoxy(20,24);
	printf("Please Enter The Option: ");
	scanf("%s",b);
	if(strcmp(b,"1")==0){
	    kp=fopen("Calculator.txt","a");
        check_fun();
		gotoxy(20,25);
		printf("Enter Accounting: ");
		scanf("%f",&dec.Account_ing);
		fseek(kp,54,0);
		fprintf(kp,"%f",dec.Account_ing);
		gotoxy(20,26);
		printf("Data Saved Press Enter");
        fclose(kp);
		getch();
	}
	if(strcmp(b,"2")==0){
		gotoxy(20,25);
		kp=fopen("Calculator.txt","a");
        check_fun();
		printf("Enter Bank Charges: ");
		scanf("%f",&dec.Bank_Charges);
		fseek(kp,72,0);
		fprintf(kp,"%f",dec.Bank_Charges);
		gotoxy(20,26);
		printf("Data Saved Press Enter");
		fclose(kp);
		getch();
	}
	if(strcmp(b,"3")==0){
		gotoxy(20,25);
		kp=fopen("Calculator.txt","a");
        check_fun();
		printf("Enter Board Charges: ");
		scanf("%f",&dec.Board_Expense);
		fseek(kp,90,0);
		fprintf(kp,"%f",dec.Board_Expense);
		gotoxy(20,26);
		printf("Data Saved Press Enter");
		fclose(kp);
		getch();
	}
	if(strcmp(b,"4")==0){
		gotoxy(20,25);
		kp=fopen("Calculator.txt","a");
        check_fun();
		printf("Enter Conference Charges: ");
		scanf("%f",&dec.Conferences);
		fseek(kp,108,0);
		fprintf(kp,"%f",dec.Conferences);
		gotoxy(20,26);
		printf("Data Saved Press Enter");
		fclose(kp);
		getch();
	}
	if(strcmp(b,"5")==0){
		gotoxy(20,25);
		kp=fopen("Calculator.txt","a");
        check_fun();
		printf("Enter Internet Charges: ");
		scanf("%f",&dec.Internet);
		fseek(kp,126,0);
		fprintf(kp,"%f",dec.Internet);
		gotoxy(20,26);
		printf("Data Saved Press Enter");
		fclose(kp);
		getch();
	}
	if(strcmp(b,"6")==0){
		gotoxy(20,25);
		kp=fopen("Calculator.txt","a");
        check_fun();
		printf("Enter Liability Insurance Charges: ");
		scanf("%f",&dec.Liability_Insurance);
		fseek(kp,144,0);
		fprintf(kp,"%f",dec.Liability_Insurance);
		gotoxy(20,26);
		printf("Data Saved Press Enter");
		fclose(kp);
		getch();
	}
	if(strcmp(b,"7")==0){
		gotoxy(20,25);
		kp=fopen("Calculator.txt","a");
        check_fun();
		printf("Enter Miscellaneous Charges: ");
		scanf("%f",&dec.Misc);
		fseek(kp,162,0);
		fprintf(kp,"%f",dec.Misc);
		gotoxy(20,26);
		fclose(kp);
		printf("Data Saved Press Enter");
		getch();
	}
	if(strcmp(b,"8")==0){
		gotoxy(20,25);
		kp=fopen("Calculator.txt","a");
        check_fun();
		printf("Enter Office Equipment Charges: ");
		scanf("%f",&dec.Office_Equipment);
		fseek(kp,180,0);
		fprintf(kp,"%f",dec.Office_Equipment);
		gotoxy(20,26);
		fclose(kp);
		printf("Data Saved Press Enter");
		getch();
	}
	if(strcmp(b,"9")==0){
		gotoxy(20,25);
		kp=fopen("Calculator.txt","a");
        check_fun();
		printf("Enter Office Charges: ");
		scanf("%f",&dec.Office_Supplies);
		fseek(kp,198,0);
		fprintf(kp,"%f",dec.Office_Supplies);
		gotoxy(20,26);
		fclose(kp);
		printf("Data Saved Press Enter");
		getch();
	}
	if(strcmp(b,"10")==0){
		gotoxy(20,25);
		kp=fopen("Calculator.txt","a");
        check_fun();
		printf("Enter Payroll Charges: ");
		scanf("%f",&dec.Payroll_Expenses);
		fseek(kp,216,0);
		fprintf(kp,"%f",dec.Payroll_Expenses);
		gotoxy(20,26);
		fclose(kp);
		printf("Data Saved Press Enter");
		getch();
	}
	if(strcmp(b,"11")==0){
		gotoxy(20,25);
		kp=fopen("Calculator.txt","a");
        check_fun();
		printf("Enter PostShip Charges: ");
		scanf("%f",&dec.Post_Ship);
		fseek(kp,234,0);
		fprintf(kp,"%f",dec.Post_Ship);
		gotoxy(20,26);
		fclose(kp);
	    printf("Data Saved Press Enter");
		getch();
	}
	if(strcmp(b,"12")==0){
		gotoxy(20,25);
		kp=fopen("Calculator.txt","a");
        check_fun();
		printf("Enter Print Charges: ");
		scanf("%f",&dec.Print);
		fseek(kp,252,0);
		fprintf(kp,"%f",dec.Print);
		gotoxy(20,26);
		fclose(kp);
		printf("Data Saved Press Enter");
		getch();
	}
	if(strcmp(b,"13")==0){
		gotoxy(20,25);
		kp=fopen("Calculator.txt","a");
        check_fun();
		printf("Enter Rent Charges: ");
		scanf("%f",&dec.Rent);
		fseek(kp,270,0);
		fprintf(kp,"%f",dec.Rent);
		gotoxy(20,26);
		fclose(kp);
		printf("Data Saved Press Enter");
		getch();
	}
	if(strcmp(b,"14")==0){
		gotoxy(20,25);
		kp=fopen("Calculator.txt","a");
        check_fun();
		printf("Enter Travel Charges: ");
		scanf("%f",&dec.Travel);
		fseek(kp,288,0);
		fprintf(kp,"%f",dec.Travel);
		gotoxy(20,26);
		fclose(kp);
		printf("Data Saved Press Enter");
		getch();

	}
	if(strcmp(b,"15")==0){
		gotoxy(20,25);
		kp=fopen("Calculator.txt","a");
        check_fun();
		printf("Enter Utility Charges: ");
		scanf("%f",&dec.Utility);
		fseek(kp,306,0);
		fprintf(kp,"%f",dec.Utility);
		gotoxy(20,26);
		fclose(kp);
		printf("Data Saved Press Enter");
		getch();
	}
	if(strcmp(b,"0")==0){
		system("cls");
		break;
	}
	if(!(strcmp(b,"1")==0|| strcmp(b,"2")==0 || strcmp(b,"3")==0 || strcmp(b,"4")==0 || strcmp(b,"5")==0 || strcmp(b,"6")==0 ||
	    strcmp(b,"7")==0 || strcmp(b,"8")==0 || strcmp(b,"9")==0 || strcmp(b,"10")==0 || strcmp(b,"11")==0 || strcmp(b,"12")==0 ||
		strcmp(b,"13")==0 || strcmp(b,"14")==0 || strcmp(b,"15")==0 || strcmp(b,"0")==0)){
		gotoxy(10,27);
		printf("Wrong Choice Choose The Right One Please Press Enter To Continue");
		getch();
		}system("cls");
		}
}
if(view_inc==0){
	view_income();
}
if(modify_info==0){
system("cls");
char d[1];
 m: while(true){
    gotoxy(20,12);
	printf("Modify Income         Press[1]");
	gotoxy(20,14);
	printf("Modify Expences       Press[2]");
	gotoxy(20,16);
	printf("Return To Main Menu   Press[0]");
	scanf("%s",d);
	if(strcmp(d,"1")==0){
	int z;
	system("cls");
	while(true){
	gotoxy(20,6);
	printf("Modify Donations         Press[1]");
	gotoxy(20,8);
	printf("Modify Grants            Press[2]");
	gotoxy(20,10);
	printf("Modify Miscellaneous     Press[3]");
	gotoxy(20,12);
	printf("Return To Previous Menu  Press[0]");
	scanf("%d",&z);
	switch(z){
	case 0:system("cls");
	goto m;
	break;
	case 1: gotoxy(20,14);
	printf("Enter Amount: ");
	kp=fopen("Calculator.txt","r+");
    check_fun();
	scanf("%f",&inc.donations);
	//fseek(kp,0,0);
	//fscanf(kp,"%f",&inc.donations);
	fseek(kp,18,0);
	fscanf(kp,"%f",&inc.grants);
	fseek(kp,36,0);
	fscanf(kp,"%f",&inc.misc);
    fseek(kp,54,0);
    fscanf(kp,"%f",&dec.Account_ing);
    fseek(kp,72,0);
	fscanf(kp,"%f",&dec.Bank_Charges);
	fseek(kp,90,0);
	fscanf(kp,"%f",&dec.Board_Expense);
	fseek(kp,108,0);
	fscanf(kp,"%f",&dec.Conferences);
	fseek(kp,126,0);
	fscanf(kp,"%f",&dec.Internet);
	fseek(kp,144,0);
	fscanf(kp,"%f",&dec.Liability_Insurance);
	fseek(kp,162,0);
	fscanf(kp,"%f",&dec.Misc);
	fseek(kp,180,0);
	fscanf(kp,"%f",&dec.Office_Equipment);
	fseek(kp,198,0);
	fscanf(kp,"%f",&dec.Office_Supplies);
	fseek(kp,216,0);
	fscanf(kp,"%f",&dec.Payroll_Expenses);
	fseek(kp,234,0);
	fscanf(kp,"%f",&dec.Post_Ship);
	fseek(kp,252,0);
	fscanf(kp,"%f",&dec.Print);
	fseek(kp,270,0);
	fscanf(kp,"%f",&dec.Rent);
	fseek(kp,288,0);
	fscanf(kp,"%f",&dec.Travel);
	fseek(kp,306,0);
	fscanf(kp,"%f",&dec.Utility);

	fseek(kp,0,0);
	fprintf(kp,"%f",inc.donations);
    fseek(kp,18,0);
	fprintf(kp,"%f",inc.grants);
	fseek(kp,36,0);
	fprintf(kp,"%f",inc.misc);
    fseek(kp,54,0);
    fprintf(kp,"%f",dec.Account_ing);
    fseek(kp,72,0);
	fprintf(kp,"%f",dec.Bank_Charges);
	fseek(kp,90,0);
	fprintf(kp,"%f",dec.Board_Expense);
	fseek(kp,108,0);
	fprintf(kp,"%f",dec.Conferences);
	fseek(kp,126,0);
	fprintf(kp,"%f",dec.Internet);
	fseek(kp,144,0);
	fprintf(kp,"%f",dec.Liability_Insurance);
	fseek(kp,162,0);
	fprintf(kp,"%f",dec.Misc);
	fseek(kp,180,0);
	fprintf(kp,"%f",dec.Office_Equipment);
	fseek(kp,198,0);
	fprintf(kp,"%f",dec.Office_Supplies);
	fseek(kp,216,0);
	fprintf(kp,"%f",dec.Payroll_Expenses);
	fseek(kp,234,0);
	fprintf(kp,"%f",dec.Post_Ship);
	fseek(kp,252,0);
	fprintf(kp,"%f",dec.Print);
	fseek(kp,270,0);
	fprintf(kp,"%f",dec.Rent);
	fseek(kp,288,0);
	fprintf(kp,"%f",dec.Travel);
	fseek(kp,306,0);
	fprintf(kp,"%f",dec.Utility);
	gotoxy(20,15);
	fclose(kp);
	printf("Data Saved Press Enter");
	getch();
	break;
	case 2:
	gotoxy(20,14);
	kp=fopen("Calculator.txt","r+");
    check_fun();
	printf("Enter Amount: ");
	scanf("%f",&inc.grants);
	fseek(kp,0,0);
	fscanf(kp,"%f",&inc.donations);
	//fseek(kp,18,0);
	//fscanf(kp,"%f",&inc.grants);
	fseek(kp,36,0);
	fscanf(kp,"%f",&inc.misc);
    fseek(kp,54,0);
    fscanf(kp,"%f",&dec.Account_ing);
    fseek(kp,72,0);
	fscanf(kp,"%f",&dec.Bank_Charges);
	fseek(kp,90,0);
	fscanf(kp,"%f",&dec.Board_Expense);
	fseek(kp,108,0);
	fscanf(kp,"%f",&dec.Conferences);
	fseek(kp,126,0);
	fscanf(kp,"%f",&dec.Internet);
	fseek(kp,144,0);
	fscanf(kp,"%f",&dec.Liability_Insurance);
	fseek(kp,162,0);
	fscanf(kp,"%f",&dec.Misc);
	fseek(kp,180,0);
	fscanf(kp,"%f",&dec.Office_Equipment);
	fseek(kp,198,0);
	fscanf(kp,"%f",&dec.Office_Supplies);
	fseek(kp,216,0);
	fscanf(kp,"%f",&dec.Payroll_Expenses);
	fseek(kp,234,0);
	fscanf(kp,"%f",&dec.Post_Ship);
	fseek(kp,252,0);
	fscanf(kp,"%f",&dec.Print);
	fseek(kp,270,0);
	fscanf(kp,"%f",&dec.Rent);
	fseek(kp,288,0);
	fscanf(kp,"%f",&dec.Travel);
	fseek(kp,306,0);
	fscanf(kp,"%f",&dec.Utility);

	fseek(kp,0,0);
	fprintf(kp,"%f",inc.donations);
    fseek(kp,18,0);
	fprintf(kp,"%f",inc.grants);
	fseek(kp,36,0);
	fprintf(kp,"%f",inc.misc);
    fseek(kp,54,0);
    fprintf(kp,"%f",dec.Account_ing);
    fseek(kp,72,0);
	fprintf(kp,"%f",dec.Bank_Charges);
	fseek(kp,90,0);
	fprintf(kp,"%f",dec.Board_Expense);
	fseek(kp,108,0);
	fprintf(kp,"%f",dec.Conferences);
	fseek(kp,126,0);
	fprintf(kp,"%f",dec.Internet);
	fseek(kp,144,0);
	fprintf(kp,"%f",dec.Liability_Insurance);
	fseek(kp,162,0);
	fprintf(kp,"%f",dec.Misc);
	fseek(kp,180,0);
	fprintf(kp,"%f",dec.Office_Equipment);
	fseek(kp,198,0);
	fprintf(kp,"%f",dec.Office_Supplies);
	fseek(kp,216,0);
	fprintf(kp,"%f",dec.Payroll_Expenses);
	fseek(kp,234,0);
	fprintf(kp,"%f",dec.Post_Ship);
	fseek(kp,252,0);
	fprintf(kp,"%f",dec.Print);
	fseek(kp,270,0);
	fprintf(kp,"%f",dec.Rent);
	fseek(kp,288,0);
	fprintf(kp,"%f",dec.Travel);
	fseek(kp,306,0);
	fprintf(kp,"%f",dec.Utility);
	gotoxy(20,15);
	printf("Data Saved Press Enter");
	fclose(kp);
	getch();
	break;
	case 3:gotoxy(20,14);
	kp=fopen("Calculator.txt","r+");
    check_fun();
	printf("Enter Amount: ");
	scanf("%f",&inc.misc);
	fseek(kp,0,0);
	fscanf(kp,"%f",&inc.donations);
	fseek(kp,18,0);
	fscanf(kp,"%f",&inc.grants);
	//fseek(kp,36,0);
	//fscanf(kp,"%f",&inc.misc);
    fseek(kp,54,0);
    fscanf(kp,"%f",&dec.Account_ing);
    fseek(kp,72,0);
	fscanf(kp,"%f",&dec.Bank_Charges);
	fseek(kp,90,0);
	fscanf(kp,"%f",&dec.Board_Expense);
	fseek(kp,108,0);
	fscanf(kp,"%f",&dec.Conferences);
	fseek(kp,126,0);
	fscanf(kp,"%f",&dec.Internet);
	fseek(kp,144,0);
	fscanf(kp,"%f",&dec.Liability_Insurance);
	fseek(kp,162,0);
	fscanf(kp,"%f",&dec.Misc);
	fseek(kp,180,0);
	fscanf(kp,"%f",&dec.Office_Equipment);
	fseek(kp,198,0);
	fscanf(kp,"%f",&dec.Office_Supplies);
	fseek(kp,216,0);
	fscanf(kp,"%f",&dec.Payroll_Expenses);
	fseek(kp,234,0);
	fscanf(kp,"%f",&dec.Post_Ship);
	fseek(kp,252,0);
	fscanf(kp,"%f",&dec.Print);
	fseek(kp,270,0);
	fscanf(kp,"%f",&dec.Rent);
	fseek(kp,288,0);
	fscanf(kp,"%f",&dec.Travel);
	fseek(kp,306,0);
	fscanf(kp,"%f",&dec.Utility);
	fseek(kp,0,0);
	fprintf(kp,"%f",inc.donations);
    fseek(kp,18,0);
	fprintf(kp,"%f",inc.grants);
	fseek(kp,36,0);
	fprintf(kp,"%f",inc.misc);
    fseek(kp,54,0);
    fprintf(kp,"%f",dec.Account_ing);
    fseek(kp,72,0);
	fprintf(kp,"%f",dec.Bank_Charges);
	fseek(kp,90,0);
	fprintf(kp,"%f",dec.Board_Expense);
	fseek(kp,108,0);
	fprintf(kp,"%f",dec.Conferences);
	fseek(kp,126,0);
	fprintf(kp,"%f",dec.Internet);
	fseek(kp,144,0);
	fprintf(kp,"%f",dec.Liability_Insurance);
	fseek(kp,162,0);
	fprintf(kp,"%f",dec.Misc);
	fseek(kp,180,0);
	fprintf(kp,"%f",dec.Office_Equipment);
	fseek(kp,198,0);
	fprintf(kp,"%f",dec.Office_Supplies);
	fseek(kp,216,0);
	fprintf(kp,"%f",dec.Payroll_Expenses);
	fseek(kp,234,0);
	fprintf(kp,"%f",dec.Post_Ship);
	fseek(kp,252,0);
	fprintf(kp,"%f",dec.Print);
	fseek(kp,270,0);
	fprintf(kp,"%f",dec.Rent);
	fseek(kp,288,0);
	fprintf(kp,"%f",dec.Travel);
	fseek(kp,306,0);
	fprintf(kp,"%f",dec.Utility);
	gotoxy(20,15);
	fclose(kp);
	printf("Data Saved Press Enter");
	getch();
	break;
	default:
	gotoxy(16,16);
	printf("Wrong Choice Choose The Right One Please Press Enter To Continue");
	getch();
	system("cls");
	}system("cls");
	}
}
if(strcmp(d,"2")==0){
system("cls");
int x;
while(true){
	gotoxy(20,4);
	printf("Modify Accounting          Press[1]");
	gotoxy(20,5);
	printf("Modify Bank Charges        Press[2]");
	gotoxy(20,6);
	printf("Modify Board Expences      Press[3]");
	gotoxy(20,7);
	printf("Modify Conference          Press[4]");
	gotoxy(20,8);
	printf("Modify Liability Insurance Press[5]");
	gotoxy(20,9);
	printf("Modify Miscellaneous       Press[6]");
	gotoxy(20,10);
	printf("Modify Office Equipment    Press[7]");
	gotoxy(20,11);
	printf("Modify Office Supplies     Press[8]");
	gotoxy(20,12);
	printf("Modify Payroll Expences    Press[9]");
	gotoxy(20,13);
	printf("Modify Postage Shipping    Press[10]");
	gotoxy(20,14);
	printf("Modify Printing            Press[11]");
	gotoxy(20,15);
	printf("Modify Rent                Press[12]");
	gotoxy(20,16);
	printf("Modify Travel              Press[13]");
	gotoxy(20,17);
	printf("Modify Utilities           Press[14]");
	gotoxy(20,18);
	printf("Modify Internet            Press[15]");
	gotoxy(20,19);
	printf("Return To Previous Menu    Press[0]");
	gotoxy(20,20);
	printf("Please Enter The Option: ");
	scanf("%d",&x);
	switch(x){
		case 0: system("cls");
		goto m;
		break;
		case 1:gotoxy(20,22);
		printf("Enter Amount: ");
		kp=fopen("Calculator.txt","r+");
        check_fun();
		scanf("%f",&dec.Account_ing);
		fseek(kp,0,0);
	fscanf(kp,"%f",&inc.donations);
	fseek(kp,18,0);
	fscanf(kp,"%f",&inc.grants);
	fseek(kp,36,0);
	fscanf(kp,"%f",&inc.misc);
   // fseek(kp,54,0);
    //fscanf(kp,"%f",&dec.Account_ing);
    fseek(kp,72,0);
	fscanf(kp,"%f",&dec.Bank_Charges);
	fseek(kp,90,0);
	fscanf(kp,"%f",&dec.Board_Expense);
	fseek(kp,108,0);
	fscanf(kp,"%f",&dec.Conferences);
	fseek(kp,126,0);
	fscanf(kp,"%f",&dec.Internet);
	fseek(kp,144,0);
	fscanf(kp,"%f",&dec.Liability_Insurance);
	fseek(kp,162,0);
	fscanf(kp,"%f",&dec.Misc);
	fseek(kp,180,0);
	fscanf(kp,"%f",&dec.Office_Equipment);
	fseek(kp,198,0);
	fscanf(kp,"%f",&dec.Office_Supplies);
	fseek(kp,216,0);
	fscanf(kp,"%f",&dec.Payroll_Expenses);
	fseek(kp,234,0);
	fscanf(kp,"%f",&dec.Post_Ship);
	fseek(kp,252,0);
	fscanf(kp,"%f",&dec.Print);
	fseek(kp,270,0);
	fscanf(kp,"%f",&dec.Rent);
	fseek(kp,288,0);
	fscanf(kp,"%f",&dec.Travel);
	fseek(kp,306,0);
	fscanf(kp,"%f",&dec.Utility);
	fseek(kp,0,0);
	fprintf(kp,"%f",inc.donations);
    fseek(kp,18,0);
	fprintf(kp,"%f",inc.grants);
	fseek(kp,36,0);
	fprintf(kp,"%f",inc.misc);
    fseek(kp,54,0);
    fprintf(kp,"%f",dec.Account_ing);
    fseek(kp,72,0);
	fprintf(kp,"%f",dec.Bank_Charges);
	fseek(kp,90,0);
	fprintf(kp,"%f",dec.Board_Expense);
	fseek(kp,108,0);
	fprintf(kp,"%f",dec.Conferences);
	fseek(kp,126,0);
	fprintf(kp,"%f",dec.Internet);
	fseek(kp,144,0);
	fprintf(kp,"%f",dec.Liability_Insurance);
	fseek(kp,162,0);
	fprintf(kp,"%f",dec.Misc);
	fseek(kp,180,0);
	fprintf(kp,"%f",dec.Office_Equipment);
	fseek(kp,198,0);
	fprintf(kp,"%f",dec.Office_Supplies);
	fseek(kp,216,0);
	fprintf(kp,"%f",dec.Payroll_Expenses);
	fseek(kp,234,0);
	fprintf(kp,"%f",dec.Post_Ship);
	fseek(kp,252,0);
	fprintf(kp,"%f",dec.Print);
	fseek(kp,270,0);
	fprintf(kp,"%f",dec.Rent);
	fseek(kp,288,0);
	fprintf(kp,"%f",dec.Travel);
	fseek(kp,306,0);
	fprintf(kp,"%f",dec.Utility);
		gotoxy(20,23);
		fclose(kp);
		printf("Data Saved Press Enter");
		getch();
		break;
		case 2:gotoxy(20,22);
		printf("Enter Amount: ");
		kp=fopen("Calculator.txt","r+");
        check_fun();
		scanf("%f",&dec.Bank_Charges);
		fseek(kp,0,0);
	fscanf(kp,"%f",&inc.donations);
	fseek(kp,18,0);
	fscanf(kp,"%f",&inc.grants);
	fseek(kp,36,0);
	fscanf(kp,"%f",&inc.misc);
    fseek(kp,54,0);
    fscanf(kp,"%f",&dec.Account_ing);
   // fseek(kp,72,0);
	//fscanf(kp,"%f",&dec.Bank_Charges);
	fseek(kp,90,0);
	fscanf(kp,"%f",&dec.Board_Expense);
	fseek(kp,108,0);
	fscanf(kp,"%f",&dec.Conferences);
	fseek(kp,126,0);
	fscanf(kp,"%f",&dec.Internet);
	fseek(kp,144,0);
	fscanf(kp,"%f",&dec.Liability_Insurance);
	fseek(kp,162,0);
	fscanf(kp,"%f",&dec.Misc);
	fseek(kp,180,0);
	fscanf(kp,"%f",&dec.Office_Equipment);
	fseek(kp,198,0);
	fscanf(kp,"%f",&dec.Office_Supplies);
	fseek(kp,216,0);
	fscanf(kp,"%f",&dec.Payroll_Expenses);
	fseek(kp,234,0);
	fscanf(kp,"%f",&dec.Post_Ship);
	fseek(kp,252,0);
	fscanf(kp,"%f",&dec.Print);
	fseek(kp,270,0);
	fscanf(kp,"%f",&dec.Rent);
	fseek(kp,288,0);
	fscanf(kp,"%f",&dec.Travel);
	fseek(kp,306,0);
	fscanf(kp,"%f",&dec.Utility);

	fseek(kp,0,0);
	fprintf(kp,"%f",inc.donations);
    fseek(kp,18,0);
	fprintf(kp,"%f",inc.grants);
	fseek(kp,36,0);
	fprintf(kp,"%f",inc.misc);
    fseek(kp,54,0);
    fprintf(kp,"%f",dec.Account_ing);
    fseek(kp,72,0);
	fprintf(kp,"%f",dec.Bank_Charges);
	fseek(kp,90,0);
	fprintf(kp,"%f",dec.Board_Expense);
	fseek(kp,108,0);
	fprintf(kp,"%f",dec.Conferences);
	fseek(kp,126,0);
	fprintf(kp,"%f",dec.Internet);
	fseek(kp,144,0);
	fprintf(kp,"%f",dec.Liability_Insurance);
	fseek(kp,162,0);
	fprintf(kp,"%f",dec.Misc);
	fseek(kp,180,0);
	fprintf(kp,"%f",dec.Office_Equipment);
	fseek(kp,198,0);
	fprintf(kp,"%f",dec.Office_Supplies);
	fseek(kp,216,0);
	fprintf(kp,"%f",dec.Payroll_Expenses);
	fseek(kp,234,0);
	fprintf(kp,"%f",dec.Post_Ship);
	fseek(kp,252,0);
	fprintf(kp,"%f",dec.Print);
	fseek(kp,270,0);
	fprintf(kp,"%f",dec.Rent);
	fseek(kp,288,0);
	fprintf(kp,"%f",dec.Travel);
	fseek(kp,306,0);
	fprintf(kp,"%f",dec.Utility);

		gotoxy(20,23);
		fclose(kp);
		printf("Data Saved Press Enter");
		getch();
		break;
		case 3:	gotoxy(20,22);
		printf("Enter Amount: ");
		kp=fopen("Calculator.txt","r+");
        check_fun();
		scanf("%f",&dec.Board_Expense);
    fseek(kp,0,0);
	fscanf(kp,"%f",&inc.donations);
	fseek(kp,18,0);
	fscanf(kp,"%f",&inc.grants);
	fseek(kp,36,0);
	fscanf(kp,"%f",&inc.misc);
    fseek(kp,54,0);
    fscanf(kp,"%f",&dec.Account_ing);
    fseek(kp,72,0);
	fscanf(kp,"%f",&dec.Bank_Charges);
	//fseek(kp,90,0);
	//fscanf(kp,"%f",&dec.Board_Expense);
	fseek(kp,108,0);
	fscanf(kp,"%f",&dec.Conferences);
	fseek(kp,126,0);
	fscanf(kp,"%f",&dec.Internet);
	fseek(kp,144,0);
	fscanf(kp,"%f",&dec.Liability_Insurance);
	fseek(kp,162,0);
	fscanf(kp,"%f",&dec.Misc);
	fseek(kp,180,0);
	fscanf(kp,"%f",&dec.Office_Equipment);
	fseek(kp,198,0);
	fscanf(kp,"%f",&dec.Office_Supplies);
	fseek(kp,216,0);
	fscanf(kp,"%f",&dec.Payroll_Expenses);
	fseek(kp,234,0);
	fscanf(kp,"%f",&dec.Post_Ship);
	fseek(kp,252,0);
	fscanf(kp,"%f",&dec.Print);
	fseek(kp,270,0);
	fscanf(kp,"%f",&dec.Rent);
	fseek(kp,288,0);
	fscanf(kp,"%f",&dec.Travel);
	fseek(kp,306,0);
	fscanf(kp,"%f",&dec.Utility);

	fseek(kp,0,0);
	fprintf(kp,"%f",inc.donations);
    fseek(kp,18,0);
	fprintf(kp,"%f",inc.grants);
	fseek(kp,36,0);
	fprintf(kp,"%f",inc.misc);
    fseek(kp,54,0);
    fprintf(kp,"%f",dec.Account_ing);
    fseek(kp,72,0);
	fprintf(kp,"%f",dec.Bank_Charges);
	fseek(kp,90,0);
	fprintf(kp,"%f",dec.Board_Expense);
	fseek(kp,108,0);
	fprintf(kp,"%f",dec.Conferences);
	fseek(kp,126,0);
	fprintf(kp,"%f",dec.Internet);
	fseek(kp,144,0);
	fprintf(kp,"%f",dec.Liability_Insurance);
	fseek(kp,162,0);
	fprintf(kp,"%f",dec.Misc);
	fseek(kp,180,0);
	fprintf(kp,"%f",dec.Office_Equipment);
	fseek(kp,198,0);
	fprintf(kp,"%f",dec.Office_Supplies);
	fseek(kp,216,0);
	fprintf(kp,"%f",dec.Payroll_Expenses);
	fseek(kp,234,0);
	fprintf(kp,"%f",dec.Post_Ship);
	fseek(kp,252,0);
	fprintf(kp,"%f",dec.Print);
	fseek(kp,270,0);
	fprintf(kp,"%f",dec.Rent);
	fseek(kp,288,0);
	fprintf(kp,"%f",dec.Travel);
	fseek(kp,306,0);
	fprintf(kp,"%f",dec.Utility);

		gotoxy(20,23);
		fclose(kp);
		printf("Data Saved Press Enter");
		getch();
		break;
		case 4:gotoxy(20,22);
		printf("Enter Amount: ");
		kp=fopen("Calculator.txt","r+");
        check_fun();
		scanf("%f",&dec.Conferences);
    fseek(kp,0,0);
	fscanf(kp,"%f",&inc.donations);
	fseek(kp,18,0);
	fscanf(kp,"%f",&inc.grants);
	fseek(kp,36,0);
	fscanf(kp,"%f",&inc.misc);
    fseek(kp,54,0);
    fscanf(kp,"%f",&dec.Account_ing);
    fseek(kp,72,0);
	fscanf(kp,"%f",&dec.Bank_Charges);
	fseek(kp,90,0);
	fscanf(kp,"%f",&dec.Board_Expense);
	//fseek(kp,108,0);
	//fscanf(kp,"%f",&dec.Conferences);
	fseek(kp,126,0);
	fscanf(kp,"%f",&dec.Internet);
	fseek(kp,144,0);
	fscanf(kp,"%f",&dec.Liability_Insurance);
	fseek(kp,162,0);
	fscanf(kp,"%f",&dec.Misc);
	fseek(kp,180,0);
	fscanf(kp,"%f",&dec.Office_Equipment);
	fseek(kp,198,0);
	fscanf(kp,"%f",&dec.Office_Supplies);
	fseek(kp,216,0);
	fscanf(kp,"%f",&dec.Payroll_Expenses);
	fseek(kp,234,0);
	fscanf(kp,"%f",&dec.Post_Ship);
	fseek(kp,252,0);
	fscanf(kp,"%f",&dec.Print);
	fseek(kp,270,0);
	fscanf(kp,"%f",&dec.Rent);
	fseek(kp,288,0);
	fscanf(kp,"%f",&dec.Travel);
	fseek(kp,306,0);
	fscanf(kp,"%f",&dec.Utility);

	fseek(kp,0,0);
	fprintf(kp,"%f",inc.donations);
    fseek(kp,18,0);
	fprintf(kp,"%f",inc.grants);
	fseek(kp,36,0);
	fprintf(kp,"%f",inc.misc);
    fseek(kp,54,0);
    fprintf(kp,"%f",dec.Account_ing);
    fseek(kp,72,0);
	fprintf(kp,"%f",dec.Bank_Charges);
	fseek(kp,90,0);
	fprintf(kp,"%f",dec.Board_Expense);
	fseek(kp,108,0);
	fprintf(kp,"%f",dec.Conferences);
	fseek(kp,126,0);
	fprintf(kp,"%f",dec.Internet);
	fseek(kp,144,0);
	fprintf(kp,"%f",dec.Liability_Insurance);
	fseek(kp,162,0);
	fprintf(kp,"%f",dec.Misc);
	fseek(kp,180,0);
	fprintf(kp,"%f",dec.Office_Equipment);
	fseek(kp,198,0);
	fprintf(kp,"%f",dec.Office_Supplies);
	fseek(kp,216,0);
	fprintf(kp,"%f",dec.Payroll_Expenses);
	fseek(kp,234,0);
	fprintf(kp,"%f",dec.Post_Ship);
	fseek(kp,252,0);
	fprintf(kp,"%f",dec.Print);
	fseek(kp,270,0);
	fprintf(kp,"%f",dec.Rent);
	fseek(kp,288,0);
	fprintf(kp,"%f",dec.Travel);
	fseek(kp,306,0);
	fprintf(kp,"%f",dec.Utility);

		gotoxy(20,23);
		fclose(kp);
		printf("Data Saved Press Enter");
		getch();
		break;
		case 5:	gotoxy(20,22);
		kp=fopen("Calculator.txt","r+");
        check_fun();
		printf("Enter Amount: ");
		scanf("%f",&dec.Internet);
		fseek(kp,0,0);
	fscanf(kp,"%f",&inc.donations);
	fseek(kp,18,0);
	fscanf(kp,"%f",&inc.grants);
	fseek(kp,36,0);
	fscanf(kp,"%f",&inc.misc);
    fseek(kp,54,0);
    fscanf(kp,"%f",&dec.Account_ing);
    fseek(kp,72,0);
	fscanf(kp,"%f",&dec.Bank_Charges);
	fseek(kp,90,0);
	fscanf(kp,"%f",&dec.Board_Expense);
	fseek(kp,108,0);
	fscanf(kp,"%f",&dec.Conferences);
	//fseek(kp,126,0);
	//fscanf(kp,"%f",&dec.Internet);
	fseek(kp,144,0);
	fscanf(kp,"%f",&dec.Liability_Insurance);
	fseek(kp,162,0);
	fscanf(kp,"%f",&dec.Misc);
	fseek(kp,180,0);
	fscanf(kp,"%f",&dec.Office_Equipment);
	fseek(kp,198,0);
	fscanf(kp,"%f",&dec.Office_Supplies);
	fseek(kp,216,0);
	fscanf(kp,"%f",&dec.Payroll_Expenses);
	fseek(kp,234,0);
	fscanf(kp,"%f",&dec.Post_Ship);
	fseek(kp,252,0);
	fscanf(kp,"%f",&dec.Print);
	fseek(kp,270,0);
	fscanf(kp,"%f",&dec.Rent);
	fseek(kp,288,0);
	fscanf(kp,"%f",&dec.Travel);
	fseek(kp,306,0);
	fscanf(kp,"%f",&dec.Utility);

	fseek(kp,0,0);
	fprintf(kp,"%f",inc.donations);
    fseek(kp,18,0);
	fprintf(kp,"%f",inc.grants);
	fseek(kp,36,0);
	fprintf(kp,"%f",inc.misc);
    fseek(kp,54,0);
    fprintf(kp,"%f",dec.Account_ing);
    fseek(kp,72,0);
	fprintf(kp,"%f",dec.Bank_Charges);
	fseek(kp,90,0);
	fprintf(kp,"%f",dec.Board_Expense);
	fseek(kp,108,0);
	fprintf(kp,"%f",dec.Conferences);
	fseek(kp,126,0);
	fprintf(kp,"%f",dec.Internet);
	fseek(kp,144,0);
	fprintf(kp,"%f",dec.Liability_Insurance);
	fseek(kp,162,0);
	fprintf(kp,"%f",dec.Misc);
	fseek(kp,180,0);
	fprintf(kp,"%f",dec.Office_Equipment);
	fseek(kp,198,0);
	fprintf(kp,"%f",dec.Office_Supplies);
	fseek(kp,216,0);
	fprintf(kp,"%f",dec.Payroll_Expenses);
	fseek(kp,234,0);
	fprintf(kp,"%f",dec.Post_Ship);
	fseek(kp,252,0);
	fprintf(kp,"%f",dec.Print);
	fseek(kp,270,0);
	fprintf(kp,"%f",dec.Rent);
	fseek(kp,288,0);
	fprintf(kp,"%f",dec.Travel);
	fseek(kp,306,0);
	fprintf(kp,"%f",dec.Utility);

		gotoxy(20,23);
		fclose(kp);
		printf("Data Saved Press Enter");
		getch();
		break;
		case 6:	gotoxy(20,22);
		kp=fopen("Calculator.txt","r+");
        check_fun();
		printf("Enter Amount: ");
		scanf("%f",&dec.Liability_Insurance);
		fseek(kp,0,0);
	fscanf(kp,"%f",&inc.donations);
	fseek(kp,18,0);
	fscanf(kp,"%f",&inc.grants);
	fseek(kp,36,0);
	fscanf(kp,"%f",&inc.misc);
    fseek(kp,54,0);
    fscanf(kp,"%f",&dec.Account_ing);
    fseek(kp,72,0);
	fscanf(kp,"%f",&dec.Bank_Charges);
	fseek(kp,90,0);
	fscanf(kp,"%f",&dec.Board_Expense);
	fseek(kp,108,0);
	fscanf(kp,"%f",&dec.Conferences);
	fseek(kp,126,0);
	fscanf(kp,"%f",&dec.Internet);
	//fseek(kp,144,0);
	//fscanf(kp,"%f",&dec.Liability_Insurance);
	fseek(kp,162,0);
	fscanf(kp,"%f",&dec.Misc);
	fseek(kp,180,0);
	fscanf(kp,"%f",&dec.Office_Equipment);
	fseek(kp,198,0);
	fscanf(kp,"%f",&dec.Office_Supplies);
	fseek(kp,216,0);
	fscanf(kp,"%f",&dec.Payroll_Expenses);
	fseek(kp,234,0);
	fscanf(kp,"%f",&dec.Post_Ship);
	fseek(kp,252,0);
	fscanf(kp,"%f",&dec.Print);
	fseek(kp,270,0);
	fscanf(kp,"%f",&dec.Rent);
	fseek(kp,288,0);
	fscanf(kp,"%f",&dec.Travel);
	fseek(kp,306,0);
	fscanf(kp,"%f",&dec.Utility);
	fseek(kp,0,0);
	fprintf(kp,"%f",inc.donations);
    fseek(kp,18,0);
	fprintf(kp,"%f",inc.grants);
	fseek(kp,36,0);
	fprintf(kp,"%f",inc.misc);
    fseek(kp,54,0);
    fprintf(kp,"%f",dec.Account_ing);
    fseek(kp,72,0);
	fprintf(kp,"%f",dec.Bank_Charges);
	fseek(kp,90,0);
	fprintf(kp,"%f",dec.Board_Expense);
	fseek(kp,108,0);
	fprintf(kp,"%f",dec.Conferences);
	fseek(kp,126,0);
	fprintf(kp,"%f",dec.Internet);
	fseek(kp,144,0);
	fprintf(kp,"%f",dec.Liability_Insurance);
	fseek(kp,162,0);
	fprintf(kp,"%f",dec.Misc);
	fseek(kp,180,0);
	fprintf(kp,"%f",dec.Office_Equipment);
	fseek(kp,198,0);
	fprintf(kp,"%f",dec.Office_Supplies);
	fseek(kp,216,0);
	fprintf(kp,"%f",dec.Payroll_Expenses);
	fseek(kp,234,0);
	fprintf(kp,"%f",dec.Post_Ship);
	fseek(kp,252,0);
	fprintf(kp,"%f",dec.Print);
	fseek(kp,270,0);
	fprintf(kp,"%f",dec.Rent);
	fseek(kp,288,0);
	fprintf(kp,"%f",dec.Travel);
	fseek(kp,306,0);
	fprintf(kp,"%f",dec.Utility);
		gotoxy(20,23);
		fclose(kp);
		printf("Data Saved Press Enter");
		getch();
		break;
		case 7:	gotoxy(20,22);
		kp=fopen("Calculator.txt","r+");
        check_fun();
		printf("Enter Amount: ");
		scanf("%f",&dec.Misc);
		fseek(kp,0,0);
	fscanf(kp,"%f",&inc.donations);
	fseek(kp,18,0);
	fscanf(kp,"%f",&inc.grants);
	fseek(kp,36,0);
	fscanf(kp,"%f",&inc.misc);
    fseek(kp,54,0);
    fscanf(kp,"%f",&dec.Account_ing);
    fseek(kp,72,0);
	fscanf(kp,"%f",&dec.Bank_Charges);
	fseek(kp,90,0);
	fscanf(kp,"%f",&dec.Board_Expense);
	fseek(kp,108,0);
	fscanf(kp,"%f",&dec.Conferences);
	fseek(kp,126,0);
	fscanf(kp,"%f",&dec.Internet);
	fseek(kp,144,0);
	fscanf(kp,"%f",&dec.Liability_Insurance);
	//fseek(kp,162,0);
	//fscanf(kp,"%f",&dec.Misc);
	fseek(kp,180,0);
	fscanf(kp,"%f",&dec.Office_Equipment);
	fseek(kp,198,0);
	fscanf(kp,"%f",&dec.Office_Supplies);
	fseek(kp,216,0);
	fscanf(kp,"%f",&dec.Payroll_Expenses);
	fseek(kp,234,0);
	fscanf(kp,"%f",&dec.Post_Ship);
	fseek(kp,252,0);
	fscanf(kp,"%f",&dec.Print);
	fseek(kp,270,0);
	fscanf(kp,"%f",&dec.Rent);
	fseek(kp,288,0);
	fscanf(kp,"%f",&dec.Travel);
	fseek(kp,306,0);
	fscanf(kp,"%f",&dec.Utility);
	fseek(kp,0,0);
	fprintf(kp,"%f",inc.donations);
    fseek(kp,18,0);
	fprintf(kp,"%f",inc.grants);
	fseek(kp,36,0);
	fprintf(kp,"%f",inc.misc);
    fseek(kp,54,0);
    fprintf(kp,"%f",dec.Account_ing);
    fseek(kp,72,0);
	fprintf(kp,"%f",dec.Bank_Charges);
	fseek(kp,90,0);
	fprintf(kp,"%f",dec.Board_Expense);
	fseek(kp,108,0);
	fprintf(kp,"%f",dec.Conferences);
	fseek(kp,126,0);
	fprintf(kp,"%f",dec.Internet);
	fseek(kp,144,0);
	fprintf(kp,"%f",dec.Liability_Insurance);
	fseek(kp,162,0);
	fprintf(kp,"%f",dec.Misc);
	fseek(kp,180,0);
	fprintf(kp,"%f",dec.Office_Equipment);
	fseek(kp,198,0);
	fprintf(kp,"%f",dec.Office_Supplies);
	fseek(kp,216,0);
	fprintf(kp,"%f",dec.Payroll_Expenses);
	fseek(kp,234,0);
	fprintf(kp,"%f",dec.Post_Ship);
	fseek(kp,252,0);
	fprintf(kp,"%f",dec.Print);
	fseek(kp,270,0);
	fprintf(kp,"%f",dec.Rent);
	fseek(kp,288,0);
	fprintf(kp,"%f",dec.Travel);
	fseek(kp,306,0);
	fprintf(kp,"%f",dec.Utility);

		gotoxy(20,23);
		fclose(kp);
		printf("Data Saved Press Enter");
		getch();
		break;
		case 8:	gotoxy(20,22);
		kp=fopen("Calculator.txt","r+");
        check_fun();
		printf("Enter Amount: ");
		scanf("%f",&dec.Office_Equipment);
		fseek(kp,0,0);
	fscanf(kp,"%f",&inc.donations);
	fseek(kp,18,0);
	fscanf(kp,"%f",&inc.grants);
	fseek(kp,36,0);
	fscanf(kp,"%f",&inc.misc);
    fseek(kp,54,0);
    fscanf(kp,"%f",&dec.Account_ing);
    fseek(kp,72,0);
	fscanf(kp,"%f",&dec.Bank_Charges);
	fseek(kp,90,0);
	fscanf(kp,"%f",&dec.Board_Expense);
	fseek(kp,108,0);
	fscanf(kp,"%f",&dec.Conferences);
	fseek(kp,126,0);
	fscanf(kp,"%f",&dec.Internet);
	fseek(kp,144,0);
	fscanf(kp,"%f",&dec.Liability_Insurance);
	fseek(kp,162,0);
	fscanf(kp,"%f",&dec.Misc);
	//fseek(kp,180,0);
	//fscanf(kp,"%f",&dec.Office_Equipment);
	fseek(kp,198,0);
	fscanf(kp,"%f",&dec.Office_Supplies);
	fseek(kp,216,0);
	fscanf(kp,"%f",&dec.Payroll_Expenses);
	fseek(kp,234,0);
	fscanf(kp,"%f",&dec.Post_Ship);
	fseek(kp,252,0);
	fscanf(kp,"%f",&dec.Print);
	fseek(kp,270,0);
	fscanf(kp,"%f",&dec.Rent);
	fseek(kp,288,0);
	fscanf(kp,"%f",&dec.Travel);
	fseek(kp,306,0);
	fscanf(kp,"%f",&dec.Utility);
	fseek(kp,0,0);
	fprintf(kp,"%f",inc.donations);
    fseek(kp,18,0);
	fprintf(kp,"%f",inc.grants);
	fseek(kp,36,0);
	fprintf(kp,"%f",inc.misc);
    fseek(kp,54,0);
    fprintf(kp,"%f",dec.Account_ing);
    fseek(kp,72,0);
	fprintf(kp,"%f",dec.Bank_Charges);
	fseek(kp,90,0);
	fprintf(kp,"%f",dec.Board_Expense);
	fseek(kp,108,0);
	fprintf(kp,"%f",dec.Conferences);
	fseek(kp,126,0);
	fprintf(kp,"%f",dec.Internet);
	fseek(kp,144,0);
	fprintf(kp,"%f",dec.Liability_Insurance);
	fseek(kp,162,0);
	fprintf(kp,"%f",dec.Misc);
	fseek(kp,180,0);
	fprintf(kp,"%f",dec.Office_Equipment);
	fseek(kp,198,0);
	fprintf(kp,"%f",dec.Office_Supplies);
	fseek(kp,216,0);
	fprintf(kp,"%f",dec.Payroll_Expenses);
	fseek(kp,234,0);
	fprintf(kp,"%f",dec.Post_Ship);
	fseek(kp,252,0);
	fprintf(kp,"%f",dec.Print);
	fseek(kp,270,0);
	fprintf(kp,"%f",dec.Rent);
	fseek(kp,288,0);
	fprintf(kp,"%f",dec.Travel);
	fseek(kp,306,0);
	fprintf(kp,"%f",dec.Utility);

		gotoxy(20,23);
		fclose(kp);
		printf("Data Saved Press Enter");
		getch();
		break;
		case 9:	gotoxy(20,22);
		printf("Enter Amount: ");
		kp=fopen("Calculator.txt","r+");
        check_fun();
		scanf("%f",&dec.Office_Supplies);
			fseek(kp,0,0);
	fscanf(kp,"%f",&inc.donations);
	fseek(kp,18,0);
	fscanf(kp,"%f",&inc.grants);
	fseek(kp,36,0);
	fscanf(kp,"%f",&inc.misc);
    fseek(kp,54,0);
    fscanf(kp,"%f",&dec.Account_ing);
    fseek(kp,72,0);
	fscanf(kp,"%f",&dec.Bank_Charges);
	fseek(kp,90,0);
	fscanf(kp,"%f",&dec.Board_Expense);
	fseek(kp,108,0);
	fscanf(kp,"%f",&dec.Conferences);
	fseek(kp,126,0);
	fscanf(kp,"%f",&dec.Internet);
	fseek(kp,144,0);
	fscanf(kp,"%f",&dec.Liability_Insurance);
	fseek(kp,162,0);
	fscanf(kp,"%f",&dec.Misc);
	fseek(kp,180,0);
	fscanf(kp,"%f",&dec.Office_Equipment);
	//fseek(kp,198,0);
	//fscanf(kp,"%f",&dec.Office_Supplies);
	fseek(kp,216,0);
	fscanf(kp,"%f",&dec.Payroll_Expenses);
	fseek(kp,234,0);
	fscanf(kp,"%f",&dec.Post_Ship);
	fseek(kp,252,0);
	fscanf(kp,"%f",&dec.Print);
	fseek(kp,270,0);
	fscanf(kp,"%f",&dec.Rent);
	fseek(kp,288,0);
	fscanf(kp,"%f",&dec.Travel);
	fseek(kp,306,0);
	fscanf(kp,"%f",&dec.Utility);
	fseek(kp,0,0);
	fprintf(kp,"%f",inc.donations);
    fseek(kp,18,0);
	fprintf(kp,"%f",inc.grants);
	fseek(kp,36,0);
	fprintf(kp,"%f",inc.misc);
    fseek(kp,54,0);
    fprintf(kp,"%f",dec.Account_ing);
    fseek(kp,72,0);
	fprintf(kp,"%f",dec.Bank_Charges);
	fseek(kp,90,0);
	fprintf(kp,"%f",dec.Board_Expense);
	fseek(kp,108,0);
	fprintf(kp,"%f",dec.Conferences);
	fseek(kp,126,0);
	fprintf(kp,"%f",dec.Internet);
	fseek(kp,144,0);
	fprintf(kp,"%f",dec.Liability_Insurance);
	fseek(kp,162,0);
	fprintf(kp,"%f",dec.Misc);
	fseek(kp,180,0);
	fprintf(kp,"%f",dec.Office_Equipment);
	fseek(kp,198,0);
	fprintf(kp,"%f",dec.Office_Supplies);
	fseek(kp,216,0);
	fprintf(kp,"%f",dec.Payroll_Expenses);
	fseek(kp,234,0);
	fprintf(kp,"%f",dec.Post_Ship);
	fseek(kp,252,0);
	fprintf(kp,"%f",dec.Print);
	fseek(kp,270,0);
	fprintf(kp,"%f",dec.Rent);
	fseek(kp,288,0);
	fprintf(kp,"%f",dec.Travel);
	fseek(kp,306,0);
	fprintf(kp,"%f",dec.Utility);
		gotoxy(20,23);
		fclose(kp);
		printf("Data Saved Press Enter");
		getch();
		break;
		case 10:gotoxy(20,22);
		kp=fopen("Calculator.txt","r+");
        check_fun();
		printf("Enter Amount: ");
		scanf("%f",&dec.Payroll_Expenses);
			fseek(kp,0,0);
	fscanf(kp,"%f",&inc.donations);
	fseek(kp,18,0);
	fscanf(kp,"%f",&inc.grants);
	fseek(kp,36,0);
	fscanf(kp,"%f",&inc.misc);
    fseek(kp,54,0);
    fscanf(kp,"%f",&dec.Account_ing);
    fseek(kp,72,0);
	fscanf(kp,"%f",&dec.Bank_Charges);
	fseek(kp,90,0);
	fscanf(kp,"%f",&dec.Board_Expense);
	fseek(kp,108,0);
	fscanf(kp,"%f",&dec.Conferences);
	fseek(kp,126,0);
	fscanf(kp,"%f",&dec.Internet);
	fseek(kp,144,0);
	fscanf(kp,"%f",&dec.Liability_Insurance);
	fseek(kp,162,0);
	fscanf(kp,"%f",&dec.Misc);
	fseek(kp,180,0);
	fscanf(kp,"%f",&dec.Office_Equipment);
	fseek(kp,198,0);
	fscanf(kp,"%f",&dec.Office_Supplies);
	//fseek(kp,216,0);
	//fscanf(kp,"%f",&dec.Payroll_Expenses);
	fseek(kp,234,0);
	fscanf(kp,"%f",&dec.Post_Ship);
	fseek(kp,252,0);
	fscanf(kp,"%f",&dec.Print);
	fseek(kp,270,0);
	fscanf(kp,"%f",&dec.Rent);
	fseek(kp,288,0);
	fscanf(kp,"%f",&dec.Travel);
	fseek(kp,306,0);
	fscanf(kp,"%f",&dec.Utility);
	fseek(kp,0,0);
	fprintf(kp,"%f",inc.donations);
    fseek(kp,18,0);
	fprintf(kp,"%f",inc.grants);
	fseek(kp,36,0);
	fprintf(kp,"%f",inc.misc);
    fseek(kp,54,0);
    fprintf(kp,"%f",dec.Account_ing);
    fseek(kp,72,0);
	fprintf(kp,"%f",dec.Bank_Charges);
	fseek(kp,90,0);
	fprintf(kp,"%f",dec.Board_Expense);
	fseek(kp,108,0);
	fprintf(kp,"%f",dec.Conferences);
	fseek(kp,126,0);
	fprintf(kp,"%f",dec.Internet);
	fseek(kp,144,0);
	fprintf(kp,"%f",dec.Liability_Insurance);
	fseek(kp,162,0);
	fprintf(kp,"%f",dec.Misc);
	fseek(kp,180,0);
	fprintf(kp,"%f",dec.Office_Equipment);
	fseek(kp,198,0);
	fprintf(kp,"%f",dec.Office_Supplies);
	fseek(kp,216,0);
	fprintf(kp,"%f",dec.Payroll_Expenses);
	fseek(kp,234,0);
	fprintf(kp,"%f",dec.Post_Ship);
	fseek(kp,252,0);
	fprintf(kp,"%f",dec.Print);
	fseek(kp,270,0);
	fprintf(kp,"%f",dec.Rent);
	fseek(kp,288,0);
	fprintf(kp,"%f",dec.Travel);
	fseek(kp,306,0);
	fprintf(kp,"%f",dec.Utility);
		gotoxy(20,23);
		fclose(kp);
		printf("Data Saved Press Enter");
		getch();
		break;
		case 11:	gotoxy(20,22);
		kp=fopen("Calculator.txt","r+");
        check_fun();
		printf("Enter Amount: ");
		scanf("%f",&dec.Post_Ship);
			fseek(kp,0,0);
	fscanf(kp,"%f",&inc.donations);
	fseek(kp,18,0);
	fscanf(kp,"%f",&inc.grants);
	fseek(kp,36,0);
	fscanf(kp,"%f",&inc.misc);
    fseek(kp,54,0);
    fscanf(kp,"%f",&dec.Account_ing);
    fseek(kp,72,0);
	fscanf(kp,"%f",&dec.Bank_Charges);
	fseek(kp,90,0);
	fscanf(kp,"%f",&dec.Board_Expense);
	fseek(kp,108,0);
	fscanf(kp,"%f",&dec.Conferences);
	fseek(kp,126,0);
	fscanf(kp,"%f",&dec.Internet);
	fseek(kp,144,0);
	fscanf(kp,"%f",&dec.Liability_Insurance);
	fseek(kp,162,0);
	fscanf(kp,"%f",&dec.Misc);
	fseek(kp,180,0);
	fscanf(kp,"%f",&dec.Office_Equipment);
	fseek(kp,198,0);
	fscanf(kp,"%f",&dec.Office_Supplies);
	fseek(kp,216,0);
	fscanf(kp,"%f",&dec.Payroll_Expenses);
	//fseek(kp,234,0);
	//fscanf(kp,"%f",&dec.Post_Ship);
	fseek(kp,252,0);
	fscanf(kp,"%f",&dec.Print);
	fseek(kp,270,0);
	fscanf(kp,"%f",&dec.Rent);
	fseek(kp,288,0);
	fscanf(kp,"%f",&dec.Travel);
	fseek(kp,306,0);
	fscanf(kp,"%f",&dec.Utility);

	fseek(kp,0,0);
	fprintf(kp,"%f",inc.donations);
    fseek(kp,18,0);
	fprintf(kp,"%f",inc.grants);
	fseek(kp,36,0);
	fprintf(kp,"%f",inc.misc);
    fseek(kp,54,0);
    fprintf(kp,"%f",dec.Account_ing);
    fseek(kp,72,0);
	fprintf(kp,"%f",dec.Bank_Charges);
	fseek(kp,90,0);
	fprintf(kp,"%f",dec.Board_Expense);
	fseek(kp,108,0);
	fprintf(kp,"%f",dec.Conferences);
	fseek(kp,126,0);
	fprintf(kp,"%f",dec.Internet);
	fseek(kp,144,0);
	fprintf(kp,"%f",dec.Liability_Insurance);
	fseek(kp,162,0);
	fprintf(kp,"%f",dec.Misc);
	fseek(kp,180,0);
	fprintf(kp,"%f",dec.Office_Equipment);
	fseek(kp,198,0);
	fprintf(kp,"%f",dec.Office_Supplies);
	fseek(kp,216,0);
	fprintf(kp,"%f",dec.Payroll_Expenses);
	fseek(kp,234,0);
	fprintf(kp,"%f",dec.Post_Ship);
	fseek(kp,252,0);
	fprintf(kp,"%f",dec.Print);
	fseek(kp,270,0);
	fprintf(kp,"%f",dec.Rent);
	fseek(kp,288,0);
	fprintf(kp,"%f",dec.Travel);
	fseek(kp,306,0);
	fprintf(kp,"%f",dec.Utility);
	gotoxy(20,23);
	fclose(kp);
	printf("Data Saved Press Enter");
		getch();
		break;
		case 12:gotoxy(20,22);
		kp=fopen("Calculator.txt","r+");
        check_fun();
		printf("Enter Amount: ");
		scanf("%f",&dec.Print);
			fseek(kp,0,0);
	fscanf(kp,"%f",&inc.donations);
	fseek(kp,18,0);
	fscanf(kp,"%f",&inc.grants);
	fseek(kp,36,0);
	fscanf(kp,"%f",&inc.misc);
    fseek(kp,54,0);
    fscanf(kp,"%f",&dec.Account_ing);
    fseek(kp,72,0);
	fscanf(kp,"%f",&dec.Bank_Charges);
	fseek(kp,90,0);
	fscanf(kp,"%f",&dec.Board_Expense);
	fseek(kp,108,0);
	fscanf(kp,"%f",&dec.Conferences);
	fseek(kp,126,0);
	fscanf(kp,"%f",&dec.Internet);
	fseek(kp,144,0);
	fscanf(kp,"%f",&dec.Liability_Insurance);
	fseek(kp,162,0);
	fscanf(kp,"%f",&dec.Misc);
	fseek(kp,180,0);
	fscanf(kp,"%f",&dec.Office_Equipment);
	fseek(kp,198,0);
	fscanf(kp,"%f",&dec.Office_Supplies);
	fseek(kp,216,0);
	fscanf(kp,"%f",&dec.Payroll_Expenses);
	fseek(kp,234,0);
	fscanf(kp,"%f",&dec.Post_Ship);
	//fseek(kp,252,0);
	//fscanf(kp,"%f",&dec.Print);
	fseek(kp,270,0);
	fscanf(kp,"%f",&dec.Rent);
	fseek(kp,288,0);
	fscanf(kp,"%f",&dec.Travel);
	fseek(kp,306,0);
	fscanf(kp,"%f",&dec.Utility);

	fseek(kp,0,0);
	fprintf(kp,"%f",inc.donations);
    fseek(kp,18,0);
	fprintf(kp,"%f",inc.grants);
	fseek(kp,36,0);
	fprintf(kp,"%f",inc.misc);
    fseek(kp,54,0);
    fprintf(kp,"%f",dec.Account_ing);
    fseek(kp,72,0);
	fprintf(kp,"%f",dec.Bank_Charges);
	fseek(kp,90,0);
	fprintf(kp,"%f",dec.Board_Expense);
	fseek(kp,108,0);
	fprintf(kp,"%f",dec.Conferences);
	fseek(kp,126,0);
	fprintf(kp,"%f",dec.Internet);
	fseek(kp,144,0);
	fprintf(kp,"%f",dec.Liability_Insurance);
	fseek(kp,162,0);
	fprintf(kp,"%f",dec.Misc);
	fseek(kp,180,0);
	fprintf(kp,"%f",dec.Office_Equipment);
	fseek(kp,198,0);
	fprintf(kp,"%f",dec.Office_Supplies);
	fseek(kp,216,0);
	fprintf(kp,"%f",dec.Payroll_Expenses);
	fseek(kp,234,0);
	fprintf(kp,"%f",dec.Post_Ship);
	fseek(kp,252,0);
	fprintf(kp,"%f",dec.Print);
	fseek(kp,270,0);
	fprintf(kp,"%f",dec.Rent);
	fseek(kp,288,0);
	fprintf(kp,"%f",dec.Travel);
	fseek(kp,306,0);
	fprintf(kp,"%f",dec.Utility);
		gotoxy(20,23);
		fclose(kp);
		printf("Data Saved Press Enter");
		getch();
		break;
		case 13:gotoxy(20,22);
		kp=fopen("Calculator.txt","r+");
        check_fun();
		printf("Enter Amount: ");
		scanf("%f",&dec.Rent);
		fseek(kp,0,0);
	fscanf(kp,"%f",&inc.donations);
	fseek(kp,18,0);
	fscanf(kp,"%f",&inc.grants);
	fseek(kp,36,0);
	fscanf(kp,"%f",&inc.misc);
    fseek(kp,54,0);
    fscanf(kp,"%f",&dec.Account_ing);
    fseek(kp,72,0);
	fscanf(kp,"%f",&dec.Bank_Charges);
	fseek(kp,90,0);
	fscanf(kp,"%f",&dec.Board_Expense);
	fseek(kp,108,0);
	fscanf(kp,"%f",&dec.Conferences);
	fseek(kp,126,0);
	fscanf(kp,"%f",&dec.Internet);
	fseek(kp,144,0);
	fscanf(kp,"%f",&dec.Liability_Insurance);
	fseek(kp,162,0);
	fscanf(kp,"%f",&dec.Misc);
	fseek(kp,180,0);
	fscanf(kp,"%f",&dec.Office_Equipment);
	fseek(kp,198,0);
	fscanf(kp,"%f",&dec.Office_Supplies);
	fseek(kp,216,0);
	fscanf(kp,"%f",&dec.Payroll_Expenses);
	fseek(kp,234,0);
	fscanf(kp,"%f",&dec.Post_Ship);
	fseek(kp,252,0);
	fscanf(kp,"%f",&dec.Print);
	//fseek(kp,270,0);
	//fscanf(kp,"%f",&dec.Rent);
	fseek(kp,288,0);
	fscanf(kp,"%f",&dec.Travel);
	fseek(kp,306,0);
	fscanf(kp,"%f",&dec.Utility);

	fseek(kp,0,0);
	fprintf(kp,"%f",inc.donations);
    fseek(kp,18,0);
	fprintf(kp,"%f",inc.grants);
	fseek(kp,36,0);
	fprintf(kp,"%f",inc.misc);
    fseek(kp,54,0);
    fprintf(kp,"%f",dec.Account_ing);
    fseek(kp,72,0);
	fprintf(kp,"%f",dec.Bank_Charges);
	fseek(kp,90,0);
	fprintf(kp,"%f",dec.Board_Expense);
	fseek(kp,108,0);
	fprintf(kp,"%f",dec.Conferences);
	fseek(kp,126,0);
	fprintf(kp,"%f",dec.Internet);
	fseek(kp,144,0);
	fprintf(kp,"%f",dec.Liability_Insurance);
	fseek(kp,162,0);
	fprintf(kp,"%f",dec.Misc);
	fseek(kp,180,0);
	fprintf(kp,"%f",dec.Office_Equipment);
	fseek(kp,198,0);
	fprintf(kp,"%f",dec.Office_Supplies);
	fseek(kp,216,0);
	fprintf(kp,"%f",dec.Payroll_Expenses);
	fseek(kp,234,0);
	fprintf(kp,"%f",dec.Post_Ship);
	fseek(kp,252,0);
	fprintf(kp,"%f",dec.Print);
	fseek(kp,270,0);
	fprintf(kp,"%f",dec.Rent);
	fseek(kp,288,0);
	fprintf(kp,"%f",dec.Travel);
	fseek(kp,306,0);
	fprintf(kp,"%f",dec.Utility);

		gotoxy(20,23);
		fclose(kp);
		printf("Data Saved Press Enter");
		getch();
		break;
		case 14:gotoxy(20,22);
		kp=fopen("Calculator.txt","r+");
        check_fun();
		printf("Enter Amount: ");
		scanf("%f",&dec.Travel);
		fseek(kp,0,0);
	fscanf(kp,"%f",&inc.donations);
	fseek(kp,18,0);
	fscanf(kp,"%f",&inc.grants);
	fseek(kp,36,0);
	fscanf(kp,"%f",&inc.misc);
    fseek(kp,54,0);
    fscanf(kp,"%f",&dec.Account_ing);
    fseek(kp,72,0);
	fscanf(kp,"%f",&dec.Bank_Charges);
	fseek(kp,90,0);
	fscanf(kp,"%f",&dec.Board_Expense);
	fseek(kp,108,0);
	fscanf(kp,"%f",&dec.Conferences);
	fseek(kp,126,0);
	fscanf(kp,"%f",&dec.Internet);
	fseek(kp,144,0);
	fscanf(kp,"%f",&dec.Liability_Insurance);
	fseek(kp,162,0);
	fscanf(kp,"%f",&dec.Misc);
	fseek(kp,180,0);
	fscanf(kp,"%f",&dec.Office_Equipment);
	fseek(kp,198,0);
	fscanf(kp,"%f",&dec.Office_Supplies);
	fseek(kp,216,0);
	fscanf(kp,"%f",&dec.Payroll_Expenses);
	fseek(kp,234,0);
	fscanf(kp,"%f",&dec.Post_Ship);
	fseek(kp,252,0);
	fscanf(kp,"%f",&dec.Print);
	fseek(kp,270,0);
	fscanf(kp,"%f",&dec.Rent);
	//fseek(kp,288,0);
	//fscanf(kp,"%f",&dec.Travel);
	fseek(kp,306,0);
	fscanf(kp,"%f",&dec.Utility);

	fseek(kp,0,0);
	fprintf(kp,"%f",inc.donations);
    fseek(kp,18,0);
	fprintf(kp,"%f",inc.grants);
	fseek(kp,36,0);
	fprintf(kp,"%f",inc.misc);
    fseek(kp,54,0);
    fprintf(kp,"%f",dec.Account_ing);
    fseek(kp,72,0);
	fprintf(kp,"%f",dec.Bank_Charges);
	fseek(kp,90,0);
	fprintf(kp,"%f",dec.Board_Expense);
	fseek(kp,108,0);
	fprintf(kp,"%f",dec.Conferences);
	fseek(kp,126,0);
	fprintf(kp,"%f",dec.Internet);
	fseek(kp,144,0);
	fprintf(kp,"%f",dec.Liability_Insurance);
	fseek(kp,162,0);
	fprintf(kp,"%f",dec.Misc);
	fseek(kp,180,0);
	fprintf(kp,"%f",dec.Office_Equipment);
	fseek(kp,198,0);
	fprintf(kp,"%f",dec.Office_Supplies);
	fseek(kp,216,0);
	fprintf(kp,"%f",dec.Payroll_Expenses);
	fseek(kp,234,0);
	fprintf(kp,"%f",dec.Post_Ship);
	fseek(kp,252,0);
	fprintf(kp,"%f",dec.Print);
	fseek(kp,270,0);
	fprintf(kp,"%f",dec.Rent);
	fseek(kp,288,0);
	fprintf(kp,"%f",dec.Travel);
	fseek(kp,306,0);
	fprintf(kp,"%f",dec.Utility);
		gotoxy(20,23);
		fclose(kp);
		printf("Data Saved Press Enter");
		getch();
		break;
		case 15:	gotoxy(20,22);
		kp=fopen("Calculator.txt","r+");
        check_fun();
		printf("Enter Amount: ");
		scanf("%f",&dec.Utility);
		fseek(kp,0,0);
	fscanf(kp,"%f",&inc.donations);
	fseek(kp,18,0);
	fscanf(kp,"%f",&inc.grants);
	fseek(kp,36,0);
	fscanf(kp,"%f",&inc.misc);
    fseek(kp,54,0);
    fscanf(kp,"%f",&dec.Account_ing);
    fseek(kp,72,0);
	fscanf(kp,"%f",&dec.Bank_Charges);
	fseek(kp,90,0);
	fscanf(kp,"%f",&dec.Board_Expense);
	fseek(kp,108,0);
	fscanf(kp,"%f",&dec.Conferences);
	fseek(kp,126,0);
	fscanf(kp,"%f",&dec.Internet);
	fseek(kp,144,0);
	fscanf(kp,"%f",&dec.Liability_Insurance);
	fseek(kp,162,0);
	fscanf(kp,"%f",&dec.Misc);
	fseek(kp,180,0);
	fscanf(kp,"%f",&dec.Office_Equipment);
	fseek(kp,198,0);
	fscanf(kp,"%f",&dec.Office_Supplies);
	fseek(kp,216,0);
	fscanf(kp,"%f",&dec.Payroll_Expenses);
	fseek(kp,234,0);
	fscanf(kp,"%f",&dec.Post_Ship);
	fseek(kp,252,0);
	fscanf(kp,"%f",&dec.Print);
	fseek(kp,270,0);
	fscanf(kp,"%f",&dec.Rent);
	fseek(kp,288,0);
	fscanf(kp,"%f",&dec.Travel);
	//fseek(kp,306,0);
	//fscanf(kp,"%f",&dec.Utility);
	fseek(kp,0,0);
	fprintf(kp,"%f",inc.donations);
    fseek(kp,18,0);
	fprintf(kp,"%f",inc.grants);
	fseek(kp,36,0);
	fprintf(kp,"%f",inc.misc);
    fseek(kp,54,0);
    fprintf(kp,"%f",dec.Account_ing);
    fseek(kp,72,0);
	fprintf(kp,"%f",dec.Bank_Charges);
	fseek(kp,90,0);
	fprintf(kp,"%f",dec.Board_Expense);
	fseek(kp,108,0);
	fprintf(kp,"%f",dec.Conferences);
	fseek(kp,126,0);
	fprintf(kp,"%f",dec.Internet);
	fseek(kp,144,0);
	fprintf(kp,"%f",dec.Liability_Insurance);
	fseek(kp,162,0);
	fprintf(kp,"%f",dec.Misc);
	fseek(kp,180,0);
	fprintf(kp,"%f",dec.Office_Equipment);
	fseek(kp,198,0);
	fprintf(kp,"%f",dec.Office_Supplies);
	fseek(kp,216,0);
	fprintf(kp,"%f",dec.Payroll_Expenses);
	fseek(kp,234,0);
	fprintf(kp,"%f",dec.Post_Ship);
	fseek(kp,252,0);
	fprintf(kp,"%f",dec.Print);
	fseek(kp,270,0);
	fprintf(kp,"%f",dec.Rent);
	fseek(kp,288,0);
	fprintf(kp,"%f",dec.Travel);
	fseek(kp,306,0);
	fprintf(kp,"%f",dec.Utility);
		gotoxy(20,23);
		fclose(kp);
		printf("Data Saved Press Enter");
		getch();
		break;
		default:gotoxy(10,27);
		printf("Wrong Choice Choose The Right One Please Press Enter To Continue");
		getch();
		system("cls");
	}system("cls");
	}
	}
if(strcmp(d,"0")==0){
	system("cls");
	break;
}
	if(!(strcmp(d,"1")==0 || strcmp(d,"2")==0 || strcmp(d,"0")==0)){
		gotoxy(15,17);
		printf("Wrong Option Please Choose The Right One ...");
		getch();
	}
system("cls");
}
}
if(!(exitopt==0 || income_opt==0 || expenc_opt==0 || view_inc==0 || modify_info==0))
{
	printf("Invalid Option Please Choose the Specified Ones");
	getch();
}
system("cls");
}
}
void view_income()
{
    float  tot_income, tot_expence, budget=0;
    char ch[1];
    kp=fopen("Calculator.txt","r");
    check_fun();
    fseek(kp,0,0);
	fscanf(kp,"%f",&inc.donations);
	fseek(kp,18,0);
	fscanf(kp,"%f",&inc.grants);
	fseek(kp,36,0);
	fscanf(kp,"%f",&inc.misc);
    fseek(kp,54,0);
    fscanf(kp,"%f",&dec.Account_ing);
    fseek(kp,72,0);
	fscanf(kp,"%f",&dec.Bank_Charges);
	fseek(kp,90,0);
	fscanf(kp,"%f",&dec.Board_Expense);
	fseek(kp,108,0);
	fscanf(kp,"%f",&dec.Conferences);
	fseek(kp,126,0);
	fscanf(kp,"%f",&dec.Internet);
	fseek(kp,144,0);
	fscanf(kp,"%f",&dec.Liability_Insurance);
	fseek(kp,162,0);
	fscanf(kp,"%f",&dec.Misc);
	fseek(kp,180,0);
	fscanf(kp,"%f",&dec.Office_Equipment);
	fseek(kp,198,0);
	fscanf(kp,"%f",&dec.Office_Supplies);
	fseek(kp,216,0);
	fscanf(kp,"%f",&dec.Payroll_Expenses);
	fseek(kp,234,0);
	fscanf(kp,"%f",&dec.Post_Ship);
	fseek(kp,252,0);
	fscanf(kp,"%f",&dec.Print);
	fseek(kp,270,0);
	fscanf(kp,"%f",&dec.Rent);
	fseek(kp,288,0);
	fscanf(kp,"%f",&dec.Travel);
	fseek(kp,306,0);
	fscanf(kp,"%f",&dec.Utility);
	fclose(kp);
 tot_income = inc.donations+inc.grants+inc.misc;
 tot_expence = dec.Account_ing+dec.Bank_Charges+dec.Board_Expense+dec.Conferences+dec.Internet+dec.Liability_Insurance+dec.Misc+dec.Office_Equipment
+dec.Office_Supplies+dec.Payroll_Expenses+dec.Post_Ship+dec.Print+dec.Rent+dec.Travel+dec.Utility;
 budget= tot_income- tot_expence;
while(true){
system("cls");
gotoxy(20,10);
printf("Total Income  = %f",tot_income);
gotoxy(20,11);
printf("Total Expence = %f",tot_expence);
gotoxy(20,12);
printf("Net Income    = %f",budget);
gotoxy(20,15);
printf("Press [0] to go To Previous Menu");
scanf("%s",ch);
if(strcmp(ch,"0")==0){
	system("cls");
	break;
}
if(!(strcmp(ch,"0"))==0){
	gotoxy(20,14);
	printf("Wrong choice Try Again");
	getch();
}system("cls");
}
}
